### PR TITLE
fix: strict types error

### LINKED ISSUE #110: Fix remaining strict types errors
With Drupal core moving towards strict types, [more info](https://github.com/localgovdrupal/localgov/issues/685) we should fix the remaining errors suppressed in the phpstan baseline.

```
 ------ ------------------------------------------------------------------------------------------
  Line   modules/contrib/localgov_step_by_step/src/Plugin/PreviewLinkAutopopulate/StepBySteps.php
 ------ ------------------------------------------------------------------------------------------
  39     Variable $overview might not be defined.
  42     Variable $overview might not be defined.
 ------ ------------------------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by millnut**
## What does this change?

Fixes #110

### CODE REVIEW

File: src/Plugin/PreviewLinkAutopopulate/StepBySteps.php [hunk 1]
```diff
@@ -36,13 +38,16 @@ public function getPreviewEntities(): array {
...
       $overview = $node->get('localgov_step_parent')->entity;
     }
-    $step_by_step_nodes[] = $overview;
 
-    // Find step-by-step pages.
-    $pages = $overview->get('localgov_step_by_step_pages')->referencedEntities();
-    foreach ($pages as $page) {
-      if ($page instanceof NodeInterface && $page->access('view')) {
-        $step_by_step_nodes[] = $page;
+    if ($overview instanceof Node) {
```
Comment (ekes) [inline src/Plugin/PreviewLinkAutopopulate/StepBySteps.php]: NodeInterface

Comment (finnlewis) [reply src/Plugin/PreviewLinkAutopopulate/StepBySteps.php]: @millnut make sense?

Comment (millnut) [reply src/Plugin/PreviewLinkAutopopulate/StepBySteps.php]: 👍 @ekes updated this one as well

**Review by ekes — APPROVED** [review]
